import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useQueryClient } from 'react-query';
import { useUser, useGames } from 'hooks';

const Home: NextPage = () => {
  const { user, isLoading } = useUser();
  const { games } = useGames(); 

  const queryClient = useQueryClient();

  console.log(games)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading ? (
        <></>
      ) : (
        <>
          {!user ? (
            <>
              <Link href={'/api/login'}>Login</Link>
            </>
          ) : (
            <>
              <h2>Hello {user.DisplayName}</h2>

              <button
                onClick={async () => {
                  await fetch('/api/auth', {
                    method: 'DELETE',
                    credentials: 'include',
                  });
                  queryClient.invalidateQueries('user');
                }}
              >
                Logout
              </button>
            </>
          )}
        </>
      )}

        
      <div className="container">
        <ul className='grid'>
          {games?.map((game) => 
            <li key={game.ID}>
              <img src={game.HeaderImageUrl} alt={game.Name} />
              <h2><a href={game.StoreUrl}>{game.Name}</a></h2>
            </li>
          )}
        </ul>
      </div>
    </>
  );
};

export default Home;
