import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useQueryClient } from 'react-query';
import { useUser, useGames } from 'hooks';
import { useRouter } from 'next/router';
import { useState } from 'react';

const Home: NextPage = () => {
  const router = useRouter();
  const [name, setName] = useState('');
  const { user, isLoading } = useUser();
  const { data, hasNextPage, fetchNextPage } = useGames({ nameParam: name });

  console.log(hasNextPage);

  const queryClient = useQueryClient();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading ? (
        <></>
      ) : (
        <>
          {!user ? (
            <>
              <Link href={'/api/login'}>Login</Link>
            </>
          ) : (
            <>
              <h2>Hello {user.DisplayName}</h2>

              <button
                onClick={async () => {
                  await fetch('/api/auth', {
                    method: 'DELETE',
                    credentials: 'include',
                  });
                  queryClient.invalidateQueries('user');
                }}
              >
                Logout
              </button>
            </>
          )}
        </>
      )}

      <div className="container">
        <input
          type="text"
          onChange={({ target }) => {
            setName(target.value);
          }}
        />
        <ul className="grid">
          {data?.pages.map((page) =>
            page.Games?.map((game: any) => (
              <li key={game.ID}>
                <img src={game.HeaderImageUrl} alt={game.Name} />
                <h2>
                  <a href={game.StoreUrl}>{game.Name}</a>
                </h2>
              </li>
            ))
          )}
        </ul>
        {hasNextPage ? (
          <>
            <button onClick={() => fetchNextPage()}>Load More</button>
          </>
        ) : (
          <></>
        )}
      </div>
    </>
  );
};

export default Home;
