import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useQueryClient } from 'react-query';
import { useUser } from 'hooks';
import styles from 'styles/Home.module.scss';

const Home: NextPage = () => {
  const { user, isLoading } = useUser();
  const queryClient = useQueryClient();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading ? (
        <></>
      ) : (
        <>
          {!user ? (
            <>
              <Link href={'/api/login'}>Login</Link>
            </>
          ) : (
            <>
              <h2>Hello {user.DisplayName}</h2>

              <button
                onClick={async () => {
                  await fetch('/api/auth', {
                    method: 'DELETE',
                    credentials: 'include',
                  });
                  queryClient.invalidateQueries('user');
                }}
              >
                Logout
              </button>
            </>
          )}
        </>
      )}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Calyx
        </a>
      </footer>
    </div>
  );
};

export default Home;
